Javascript best practices.
Fene-87/JS-Best-Practices-Review pull request #1
Opened 2023-01-23 11:13 UTC by Fene-87

In this pull request I would like to request for a review that would help me check if I have followed the Javascript best practices.
-Check if the code follows the DRY, KISS and Yagni rules.
-Check if HTML and CSS best practices have been followed.

2023-01-24 10:47 UTC, Talha-Hanif5666 commented on src/index.js
> +
I suggest you to not leave any unnecessarily blank lines in your code. This makes your code unclean and complex. Kindly fix them and remove the unnecessarily blank lines from your code.

2023-01-24 10:48 UTC, Talha-Hanif5666 commented on src/index.js
> +
I suggest you to not leave any unnecessarily blank lines in your code. This makes your code unclean and complex. Kindly fix them and remove the unnecessarily blank lines from your code.

2023-01-24 10:48 UTC, Talha-Hanif5666 commented on src/index.js
> +
I suggest you to not leave any unnecessarily blank lines in your code. This makes your code unclean and complex. Kindly fix them and remove the unnecessarily blank lines from your code.

2023-01-24 10:49 UTC, Talha-Hanif5666 commented on src/index.js
> +
Kindly remove the extra blank lines.

2023-01-24 10:54 UTC, Talha-Hanif5666 commented on src/style.css
> +}
I suggest you kindly add an empty line at the end of the CSS file.

2023-01-24 11:06 UTC, Talha-Hanif5666 requested changes
Hi @Fene-87,
Your project page is looking fantastic so far 💯  !
However, there is still some room for improvement, which can help you have better code and make your project professional ♻️ 

![157397398-00904e26-60ec-46cd-9510-240661c250ef](https://user-images.githubusercontent.com/114238556/214274923-15b27d1c-f401-4064-bf98-11b1a817fac3.gif)

### **Highlights** 🔆 
- Great work using the right GitHub Flow 💯 
- Linters are passing correctly ✔️ 
- Good commit history 👍 
Congrats on your work so far 👏 !

### **Required Changes**
- There are some issues that you still need to work on to go to the next project, but you are almost there!
- For more information, check the comments under the review 🔢

2023-01-24 16:06 UTC, Fene-87 commented on src/style.css
> +}
Thanks for the review. I will implement the changes ASAP.😃

2023-01-24 16:35 UTC, Talha-Hanif5666 approved these changes
### **Hi @Fene-87 !**
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 👍 
### **Highlights**
- All linters passing ✔️ 
- All requirements completed ✔️ 
- Professional readme file ✔️ 

![68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f436c63577241526b727131474d2f67697068792e676966](https://user-images.githubusercontent.com/114238556/214352105-4570e599-c281-40c7-8888-d5433e18f8ca.gif)

Cheers and Happy coding! 👏 👏 👏 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@Talha-Hanif5666 ] in your question so I can receive the notification.

2023-01-25 08:19 UTC, Fene-87 commented
Okay, thank you for your feedback

2023-01-25 08:20 UTC, merged